# Generated by Django 4.0.6 on 2022-07-15 06:56

from django.db import migrations, models
import dynamictemplate.filefield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('contact_1', models.CharField(max_length=14)),
                ('contact_2', models.CharField(blank=True, default=None, max_length=14, null=True)),
                ('email_1', models.EmailField(max_length=50)),
                ('email_2', models.EmailField(blank=True, default=None, max_length=50, null=True)),
                ('google_embedding_link', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_name', models.CharField(max_length=10)),
                ('logo_image', dynamictemplate.filefield.ContentRestrictionFileField(blank=True, default=None, null=True, upload_to='logo/')),
                ('active_status', models.BooleanField()),
            ],
        ),
    ]
