# Generated by Django 4.0.6 on 2022-07-15 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamictemplate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddress',
            name='active_status',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
