# Generated by Django 4.0.6 on 2022-07-15 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dynamictemplate', '0002_contactaddress_active_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactaddress',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactaddress',
            name='date_edited',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logo',
            name='date_edited',
            field=models.DateField(auto_now=True),
        ),
    ]
