# Generated by Django 4.0.6 on 2022-07-15 08:33

import django.core.validators
from django.db import migrations, models
import dynamictemplate.filefield


class Migration(migrations.Migration):

    dependencies = [
        ('dynamictemplate', '0003_contactaddress_date_added_contactaddress_date_edited_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarosulData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
                ('date_edited', models.DateField(auto_now=True)),
                ('headline_image', dynamictemplate.filefield.ContentRestrictionFileField(blank=True, default=None, null=True, upload_to='carosul/')),
                ('special_offer', models.CharField(max_length=255)),
                ('active_status', models.BooleanField()),
                ('offer_discount', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
            ],
        ),
    ]
