# Generated by Django 4.0.6 on 2022-07-16 08:14

from django.db import migrations
import dynamictemplate.filefield


class Migration(migrations.Migration):

    dependencies = [
        ('dynamictemplate', '0004_carosuldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carosuldata',
            name='headline_image',
            field=dynamictemplate.filefield.ContentRestrictionFileField(blank=True, default=None, max_length=500, null=True, upload_to='carosul/'),
        ),
    ]
